package io.testproject.generated.tests.myfirstproject;

import io.testproject.java.annotations.v2.Parameter;
import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.ParameterDirection;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.WebDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.WebTest;
import io.testproject.java.sdk.v2.tests.helpers.WebTestHelper;
import java.lang.String;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: My first Project
 * Test: testDrugiSklepPW
 * Generated by: Diana Poplawska (poplawska97@gmail.com)
 * Generated on Sun Nov 06 21:15:28 GMT 2022.
 */
@Test(
    name = "testDrugiSklepPW",
    version = "1.0"
)
public class Testdrugiskleppw implements WebTest {
  @Parameter(
      description = "Auto generated application URL parameter",
      defaultValue = "https://www.sklep.pw.edu.pl/",
      direction = ParameterDirection.INPUT
  )
  public String ApplicationURL;

  public ExecutionResult execute(WebTestHelper helper) throws FailureException {
    WebDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;

    // 1. Navigate to '{{ApplicationURL}}'
    //    Navigates the specified URL (Auto-generated)
    GeneratedUtils.sleep(500);
    booleanResult = driver.testproject().navigateToUrl(ApplicationURL);
    report.step(String.format("Navigate to '%s'",ApplicationURL), booleanResult, TakeScreenshotConditionType.Failure);

    // 2. Click 'My Account'
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[1]/ul//a[. = 'My Account']");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'My Account'", booleanResult, TakeScreenshotConditionType.Failure);

    // 3. Click 'username'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#username");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'username'", booleanResult, TakeScreenshotConditionType.Failure);

    // 4. Type 'testpwinz@outlook.com' in 'username'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#username");
    booleanResult = driver.testproject().typeText(by,"testpwinz@outlook.com");
    report.step("Type 'testpwinz@outlook.com' in 'username'", booleanResult, TakeScreenshotConditionType.Failure);

    // 5. Type 'Test9876!!' in 'password'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#password");
    booleanResult = driver.testproject().typeText(by,"Test9876!!");
    report.step("Type 'Test9876!!' in 'password'", booleanResult, TakeScreenshotConditionType.Failure);

    // 6. Send 'ENTER' key(s)
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#password");
    booleanResult = driver.testproject().sendKeys(by,GeneratedUtils.getKeys("ENTER"));
    report.step("Send 'ENTER' key(s)", booleanResult, TakeScreenshotConditionType.Failure);

    // 7. Click 'Account details'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Account details']");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'Account details'", booleanResult, TakeScreenshotConditionType.Failure);

    // 8. Clear 'account_first_name' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#account_first_name");
    booleanResult = driver.testproject().clearContents(by);
    report.step("Clear 'account_first_name' contents", booleanResult, TakeScreenshotConditionType.Failure);

    // 9. Click 'account_first_name'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#account_first_name");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'account_first_name'", booleanResult, TakeScreenshotConditionType.Failure);

    // 10. Type 'Diana' in 'account_first_name'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#account_first_name");
    booleanResult = driver.testproject().typeText(by,"Diana");
    report.step("Type 'Diana' in 'account_first_name'", booleanResult, TakeScreenshotConditionType.Failure);

    // 11. Clear 'account_last_name' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#account_last_name");
    booleanResult = driver.testproject().clearContents(by);
    report.step("Clear 'account_last_name' contents", booleanResult, TakeScreenshotConditionType.Failure);

    // 12. Click 'account_last_name'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#account_last_name");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'account_last_name'", booleanResult, TakeScreenshotConditionType.Failure);

    // 13. Type 'Popławska' in 'account_last_name'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#account_last_name");
    booleanResult = driver.testproject().typeText(by,"Popławska");
    report.step("Type 'Popławska' in 'account_last_name'", booleanResult, TakeScreenshotConditionType.Failure);

    // 14. Click 'save_account_details'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='save_account_details']");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'save_account_details'", booleanResult, TakeScreenshotConditionType.Failure);

    // 15. Is 'Account details changed successfully.' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[. = '\n		Account details changed successfully.	']");
    booleanResult = driver.testproject().isPresent(by);
    report.step("Is 'Account details changed successfully.' present?", booleanResult, TakeScreenshotConditionType.Failure);

    // 16. Click 'Logout'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Logout']");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'Logout'", booleanResult, TakeScreenshotConditionType.Failure);

    // 17. Is 'Login' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//h2[. = 'Login']");
    booleanResult = driver.testproject().isPresent(by);
    report.step("Is 'Login' present?", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
