package io.testproject.generated.tests.myfirstproject;

import io.testproject.java.annotations.v2.Parameter;
import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.ParameterDirection;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.WebDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.WebTest;
import io.testproject.java.sdk.v2.tests.helpers.WebTestHelper;
import io.testproject.proxy.addon.WebExtensions;
import io.testproject.proxy.addon.io.testproject.addons.web.element.select.SelectOptionByIndex;
import java.lang.String;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: My first Project
 * Test: testPierwszySklepPW
 * Generated by: Diana Poplawska (poplawska97@gmail.com)
 * Generated on Sun Nov 06 21:17:16 GMT 2022.
 */
@Test(
    name = "testPierwszySklepPW",
    version = "1.0"
)
public class Testpierwszyskleppw implements WebTest {
  @Parameter(
      description = "Auto generated application URL parameter",
      defaultValue = "https://www.sklep.pw.edu.pl/",
      direction = ParameterDirection.INPUT
  )
  public String ApplicationURL;

  public ExecutionResult execute(WebTestHelper helper) throws FailureException {
    WebDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;
    ExecutionResult executionresult;
    SelectOptionByIndex selectOptionByIndex;

    // 1. Navigate to '{{ApplicationURL}}'
    //    Navigates the specified URL (Auto-generated)
    GeneratedUtils.sleep(500);
    booleanResult = driver.testproject().navigateToUrl(ApplicationURL);
    report.step(String.format("Navigate to '%s'",ApplicationURL), booleanResult, TakeScreenshotConditionType.Failure);

    // 2. Click 's'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#woocommerce-product-search-field-0");
    booleanResult = driver.testproject().click(by);
    report.step("Click 's'", booleanResult, TakeScreenshotConditionType.Failure);

    // 3. Type 'koszulka' in 's'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#woocommerce-product-search-field-0");
    booleanResult = driver.testproject().typeText(by,"koszulka");
    report.step("Type 'koszulka' in 's'", booleanResult, TakeScreenshotConditionType.Failure);

    // 4. Send 'ENTER' key(s)
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#woocommerce-product-search-field-0");
    booleanResult = driver.testproject().sendKeys(by,GeneratedUtils.getKeys("ENTER"));
    report.step("Send 'ENTER' key(s)", booleanResult, TakeScreenshotConditionType.Failure);

    // 5. Click 'Select options'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[2]/a[. = 'Select options']");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'Select options'", booleanResult, TakeScreenshotConditionType.Failure);

    // 6. Click 'attribute_pa_rodzaj'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#pa_rodzaj");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'attribute_pa_rodzaj'", booleanResult, TakeScreenshotConditionType.Failure);

    // 7. Select option indexed '1' in 'attribute_pa_rodzaj'
    GeneratedUtils.sleep(500);
    selectOptionByIndex = WebExtensions.selectOptionByIndex(1);
    by = By.cssSelector("#pa_rodzaj");
    executionresult = helper.executeProxy(selectOptionByIndex, by);
    report.step("Select option indexed '1' in 'attribute_pa_rodzaj'", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 8. Click 'attribute_pa_rodzaj'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#pa_rodzaj");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'attribute_pa_rodzaj'", booleanResult, TakeScreenshotConditionType.Failure);

    // 9. Click 'attribute_pa_rozmiar'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#pa_rozmiar");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'attribute_pa_rozmiar'", booleanResult, TakeScreenshotConditionType.Failure);

    // 10. Select option indexed '1' in 'attribute_pa_rozmiar'
    GeneratedUtils.sleep(500);
    selectOptionByIndex = WebExtensions.selectOptionByIndex(1);
    by = By.cssSelector("#pa_rozmiar");
    executionresult = helper.executeProxy(selectOptionByIndex, by);
    report.step("Select option indexed '1' in 'attribute_pa_rozmiar'", executionresult == ExecutionResult.PASSED, TakeScreenshotConditionType.Failure);

    // 11. Click 'attribute_pa_rozmiar'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#pa_rozmiar");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'attribute_pa_rozmiar'", booleanResult, TakeScreenshotConditionType.Failure);

    // 12. Click 'Add to cart'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Add to cart']");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'Add to cart'", booleanResult, TakeScreenshotConditionType.Failure);

    // 13. Click 'View cart'
    GeneratedUtils.sleep(500);
    by = By.xpath("//div/a[. = 'View cart']");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'View cart'", booleanResult, TakeScreenshotConditionType.Failure);

    // 14. Click '×'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = '×']");
    booleanResult = driver.testproject().click(by);
    report.step("Click '×'", booleanResult, TakeScreenshotConditionType.Failure);

    // 15. Scroll window by ('0','304')
    GeneratedUtils.sleep(500);
    booleanResult = driver.testproject().scrollWindow(0,304);
    report.step("Scroll window by ('0','304')", booleanResult, TakeScreenshotConditionType.Failure);

    // 16. Is '“Koszulka Zespołu Pieśni i Tańca” rem...' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[. = '\n		“Koszulka Zespołu Pieśni i Tańca” removed. Undo?	']");
    booleanResult = driver.testproject().isVisible(by);
    report.step("Is '“Koszulka Zespołu Pieśni i Tańca” rem...' visible?", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
